### ISSUE TITLE
Ошибка при запуске SonarQube в связи с ошибкой в Severity правил ACC

### ISSUE THREAD

**Issue by foxxof06** [1c-syntax/sonar-bsl-plugin-community#110]
Версия плагина 1.7.0; SonqrQube 8.4.2.36762
Производится загрузка данных из АПК (выгрузка обработкой acc-export) и в некоторых правилах установлено такое
(формат reportjson; codeTitle=code)

"Code": "58",
"Type": "BUG",
**"Severity": "SKIP",**

После загрузки данных в сонар - ошибок нет, но при попытке перезагрузки Сонара получаем это:

2020.09.30 10:00:18 INFO  web[][o.s.s.r.RegisterRules] Register rules
2020.09.30 10:00:20 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalArgumentException: Severity of rule [repository=acc-rules, key=58] is not correct: SKIP
	at org.sonar.api.utils.Preconditions.checkArgument(Preconditions.java:43)
	at org.sonar.api.server.rule.internal.DefaultNewRule.setSeverity(DefaultNewRule.java:115)
	at org.sonar.api.server.rule.internal.DefaultNewRule.setSeverity(DefaultNewRule.java:49)
	at com.github._1c_syntax.bsl.sonar.acc.ACCRuleDefinition.createRule(ACCRuleDefinition.java:77)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.github._1c_syntax.bsl.sonar.acc.ACCRuleDefinition.lambda$loadRules$1(ACCRuleDefinition.java:65)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at com.github._1c_syntax.bsl.sonar.acc.ACCRuleDefinition.loadRules(ACCRuleDefinition.java:65)
	at com.github._1c_syntax.bsl.sonar.acc.ACCRuleDefinition.define(ACCRuleDefinition.java:53)
	at org.sonar.server.rule.RuleDefinitionsLoader.load(RuleDefinitionsLoader.java:53)
	at org.sonar.server.rule.RegisterRules.start(RegisterRules.java:120)
	at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:48)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:85)
	at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:46)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:82)
	at org.sonar.server.platform.PlatformImpl.executeStartupTasks(PlatformImpl.java:198)
	at org.sonar.server.platform.PlatformImpl.access$400(PlatformImpl.java:46)
	at org.sonar.server.platform.PlatformImpl$1.lambda$doRun$1(PlatformImpl.java:122)
	at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.runIfNotAborted(PlatformImpl.java:370)
	at org.sonar.server.platform.PlatformImpl$1.doRun(PlatformImpl.java:122)
	at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.run(PlatformImpl.java:354)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020.09.30 10:00:20 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process

**Comment by nixel2007** [comment]
Кажется, для начала стоит доработать acc-export (@otymko). Но и на стороне плагина стоит добавить валидацию.

Как оно вообще загрузилось? @qtLex ?

**Comment by Stepa86** [comment]
**SKIP** проставляют мои костыли, вырезать которые нужно через https://github.com/Stepa86/stebi

Причем **SKIP** устанавливает либо acc-export если в нем специально это настроить и сам же его вырезает, либо все тот же https://github.com/Stepa86/stebi на этапе применения настроек. В любом случае он не должен просачиваться в итоговый джсон

**Comment by qtLex** [comment]
@foxxof06  f в какое свойство загружаете json?

**Comment by foxxof06** [comment]
1. SKIP действительно ставит acc-export при выгрузке
2. Изначально использовал конвеер для Jenkins от @Stepa86 , но сейчас гружу без, т.е. сейчас обработки выгруженных данных не происходит. Версия обработки 1.3.0
acc.check=false;
acc.recreateProject=false;
acc.exportRules=true;
acc.titleError=code;
acc.format=reportjson

3. Вопрос как раз и связан с тем что то ли сам Сонар, то ли плагин, позволяет загружать некорректный Severity

**Comment by foxxof06** [comment]
> 
> 
> @foxxof06 а в какое свойство загружаете json?

Не понял... можно поподробнее?

**Comment by qtLex** [comment]
> Не понял... можно поподробнее?

@foxxof06  Вы ответили на вопрос предыдущим постом.

Обработка rules-export-for-sonarqube формирует таблицу с правилами в которой Type и Severity определяются по уровню критичности в АПК и [наработках @Stepa86](https://github.com/Stepa86/jenkins-pipeline-1C-to-sonar/blob/9016537f25ddeb11fb703962f1f2cb1da893bfa8/Sonar/settings.json) . В этих наработках есть SKIP. По умолчанию такие правила отключены. Их было не много и единого шаблона для замены Severity не придумал, просто убрал их руками. 

Для плагина работы файл выгруженный с помощь rules-export-for-sonarqube, не должен содержать SKIP. 

> Параметр sonar.bsl.acc.createExternalIssues несколько раз менял, видимо в какой-то из попыток все эти правила и в грузились в БД Сонара. Вопрос как раз и связан с тем что то ли сам Сонар, то ли плагин, позволяет загружать некорректный Severity

Плагин не загрузил "поломанные" правила, падает как раз на их правил. Плагину не удается загрузить правила с неверным Severity. Удалите их из файла с описанием правил выгруженных обработкой rules-export-for-sonarqube или исправьте в самой обработке и сохраните файл повторно.

В плагин вшит базовый набор правил из АПК. Выгружать свой файл обработкой нужно только если:
- Есть свои правила в АПК. Тогда достаточно выгрузить только их.
- Требуется поменять настойки правил type, severity, время на исправление и т.д.

**Comment by qtLex** [comment]
В обработку ules-export-for-sonarqube добавлю валидацию выходного файла

**Comment by foxxof06** [comment]
> 
> 
> > Не понял... можно поподробнее?
> 
> @foxxof06 Вы ответили на вопрос предыдущим постом.
> 
> Обработка rules-export-for-sonarqube формирует таблицу с правилами в которой Type и Severity определяются по уровню критичности в АПК и [наработках @Stepa86](https://github.com/Stepa86/jenkins-pipeline-1C-to-sonar/blob/9016537f25ddeb11fb703962f1f2cb1da893bfa8/Sonar/settings.json) . В этих наработках есть SKIP. По умолчанию такие правила отключены. Их было не много и единого шаблона для замены Severity не придумал, просто убрал их руками.
> 
> Для плагина работы файл выгруженный с помощь rules-export-for-sonarqube, не должен содержать SKIP.
> 
> > Параметр sonar.bsl.acc.createExternalIssues несколько раз менял, видимо в какой-то из попыток все эти правила и в грузились в БД Сонара. Вопрос как раз и связан с тем что то ли сам Сонар, то ли плагин, позволяет загружать некорректный Severity
> 
> Плагин не загрузил "поломанные" правила, падает как раз на их загрузке. Плагину не удается загрузить правила с неверным Severity. Удалите их из файла с описанием правил выгруженных обработкой rules-export-for-sonarqube или исправьте в самой обработке и сохраните файл повторно.
> 
> В плагин вшит базовый набор правил из АПК. Выгружать свой файл обработкой нужно только если:
> 
>     * Есть свои правила в АПК. Тогда достаточно выгрузить только их.
> 
>     * Требуется поменять настойки правил type, severity, время на исправление и т.д.

Благодарю! Действительно проблема в файле выгруженных из АПК правил. Файл переименовал и стартанул Сонар. Запустился без проблем. Переживал что ошибочные значения уже в БД Сонара и вычищать их придется вручную, но как оказалось все гораздо проще. Так же спасибо за пояснение использования внешних файлов правил АПК

**Comment by foxxof06** [comment]
@qtLex Последний вопрос в рамках этой задачи. Как заставить Сонар выполнять проверку по правилам профилей ACC?

В настройках Сонара выставлял и снимал флаг sonar.bsl.acc.enabled, однако в результатах проверки были только правила 1С BSL и единственный способ, который показал в результатах правила профиля ACC это когда грузил файл экспорта сформированного обработкой acc-export (codeTitle=code; jsonReport).

К тому же на странице описание плагина вижу:

![изображение](https://user-images.githubusercontent.com/7623101/94855129-b5d03b80-0436-11eb-8269-e2c98adcafeb.png)

Отсюда следует что все-таки использование правил ACC в плагине подразумевает загрузку данных из АПК? Но из вашего комментария следует что все-таки профили должны срабатывать.

Ниже снимок активных профилей:

![изображение](https://user-images.githubusercontent.com/7623101/94855319-ff208b00-0436-11eb-838b-03df21f407f6.png)

Если установлен данный профиль - анализ только по правилам BSL, если переключаю профиль по умолчанию на один из ACC, то в результате анализа получаю 0.

**Comment by qtLex** [comment]
> Как заставить Сонар выполнять проверку по правилам профилей ACC?

Ни как. Файл с выгруженными из АПК ошибками всегда нужен.

Плагин не умеет анализировать правила из АПК, а только позволяет их загружать как внутренние правила. Это позволяет:
* Управлять состоянием замечанием
* Хранить описание правила во внутренней wiki
* Управлять активностью правил для проектов из одного места.

Добавляет удобства не ходить каждый раз в АПК если нужно указать, что ошибка не ошибка или правило отключить.

При загрузке замечаний из АПК в плагин выполняет поиск по коду среди активных правил в профиле на проекте. Если правило найдено замечание связывается с ним. Может быть создано внешнее замечание(такое же как при загрузке genericissues), если активного правила не нашлось и установлена настройка  на создание внешних замечаний.

**Comment by foxxof06** [comment]
Спасибо за разъяснения. Закрываю.
