### ISSUE TITLE
Ошибка при сканировании

### ISSUE THREAD

**Issue by ignatovsam** [1c-syntax/sonar-bsl-plugin-community#111]
При сканировании возникает ошибка. Сканирование прерывается.
На v1.6.1 ошибки не возникало.
Предположительно связанно с новым функционалом -
**_Добавлена подсветка запросов, мелкие исправления подсветки_**

15:47:01.507 ERROR: Error during SonarScanner execution
java.lang.IllegalArgumentException: Unable to highlight file src/epf/742_Diadoc1CЗагрузкаСтатусовЭДОКонтур/Form/Модуль_ИнтеграцияУТ102/module.bsl
        at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:97)
        at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:37)
        at com.github._1c_syntax.bsl.sonar.BSLHighlighter.lambda$saveHighlighting$6(BSLHighlighter.java:170)15:47:01.510 DEBUG: 'src/epf/198_ОценкаПрибылиКофейные/Form/Отчет/module.bsl' generated metadata with charset 'UTF-8'

        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)

Caused by: java.lang.IllegalArgumentException: 41 is not a valid line offset for pointer. File src/epf/742_Diadoc1CЗагрузкаСтатусовЭДОКонтур/Form/Модуль_ИнтеграцияУТ102/

module.bsl has 3 character(s) at line 1073
        at org.sonar.api.utils.Preconditions.checkArgument(Preconditions.java:43)
        at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:339)
        at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:272)15:47:01.605 DEBUG: file:///C:/DevOps/utAddForms/src/epf/271_ПродажиПоСпецификациям/Form/Отчет/module.bsl

        at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:287)
        at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:95)
        ... 64 more

![image](https://user-images.githubusercontent.com/67896720/94879378-3ec49280-048a-11eb-90ae-61fc2990c6eb.png)

**Comment by asosnoviy** [comment]
@ignatovsam приложите пожалуйста кусок модуля в виде текстового файла

**Comment by ignatovsam** [comment]
[module.txt](https://github.com/1c-syntax/sonar-bsl-plugin-community/files/5317570/module.txt)

**Comment by asosnoviy** [comment]
```
Предупреждение(НСтр("en='A line itselft or the descending lines cannot be selected for copying. Select another one.';ru='Нельзя выбирать в качестве копируемой строки саму строку"
                "или подчиненные ей строки. Выберите другую строку.'"));
```

**Comment by artbear** [comment]
у нас аналогично падает анализ на расширениях, где используются директивы #Вставка #Удаление и т.п.

юзаем последний плагин 1.8.1
и проблемы начались, похоже, после его установки

я правильно понимаю, что такая ошибка может возникать при ошибке анализа исходника модуля расширения?
как избавиться от ошибки?

@nixel2007 не связано с твоим исправлением в https://github.com/1c-syntax/sonar-bsl-plugin-community/pull/120 ?

связанный ишуз https://github.com/1c-syntax/bsl-language-server/issues/1473

**Comment by nixel2007** [comment]
@artbear нет, #120 используется для сохранения данных о диагностиках, а не хайлайт.
По идее эта проблема должна была уйти в 1.8.1, неужели до сих пор воспроизводится?

**Comment by artbear** [comment]
@nixel2007 Сделать новый ишуз, чтобы проблема была видна и не затерялась?

**Comment by artbear** [comment]
>По идее эта проблема должна была уйти в 1.8.1, неужели до сих пор воспроизводится?

у нас проблема как раз и появилась сразу после перехода на 1.8.1 (
до этгого падения анализа не было
только выдавалась замечание ошибка разбора модуля и все, как я и написал в связанном ишузе

**Comment by nixel2007** [comment]
Завел https://github.com/1c-syntax/sonar-bsl-plugin-community/issues/121
