### ISSUE TITLE
Ошибка при анализе УТ и ЕРП

### ISSUE THREAD

**Issue by nagdevops2** [1c-syntax/sonar-bsl-plugin-community#125]
Здравствуйте.
Ошибки:

УТ подобных ошибок много

ERROR: Can't compute TextRange for given Range
java.lang.IllegalArgumentException: 57 is not a valid line offset for pointer. File Trade/CommonModules/УправлениеКонтактнойИнформацией/Ext/Module.bsl has 55 character(s) at line 2365
	at org.sonar.api.utils.Preconditions.checkArgument(Preconditions.java:43)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:339)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:272)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:287)
	at com.github._1c_syntax.bsl.sonar.IssuesLoader.getTextRange(IssuesLoader.java:231)
	at com.github._1c_syntax.bsl.sonar.IssuesLoader.getNewIssueLocation(IssuesLoader.java:215)
	at com.github._1c_syntax.bsl.sonar.IssuesLoader.createIssue(IssuesLoader.java:99)
	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.lambda$processFile$5(BSLCoreSensor.java:197)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.processFile(BSLCoreSensor.java:197)
	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.lambda$execute$3(BSLCoreSensor.java:172)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

![image](https://user-images.githubusercontent.com/82443902/131610164-9b4cc488-5198-4bc0-a374-0f10a64df837.png)

ЕРП единичные случаи:

ERROR: Can't compute TextRange for given Range
java.lang.IllegalArgumentException: 83 is not a valid line offset for pointer. File ERP/CommonModules/НАГ_УниверсальныеМеханизмы/Ext/Module.bsl has 12 character(s) at line 1612
	at org.sonar.api.utils.Preconditions.checkArgument(Preconditions.java:43)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:339)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:272)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:287)
	at com.github._1c_syntax.bsl.sonar.IssuesLoader.getTextRange(IssuesLoader.java:231)
	at com.github._1c_syntax.bsl.sonar.IssuesLoader.getNewIssueLocation(IssuesLoader.java:215)
	at com.github._1c_syntax.bsl.sonar.IssuesLoader.createIssue(IssuesLoader.java:99)
	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.lambda$processFile$5(BSLCoreSensor.java:197)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.processFile(BSLCoreSensor.java:197)
	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.lambda$execute$3(BSLCoreSensor.java:172)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

![image](https://user-images.githubusercontent.com/82443902/131610393-4105b953-03a0-4fbf-b3b2-1e06a7aabca8.png)

**Comment by nagdevops2** [comment]
SQ Community EditionВерсия 8.8 (build 42792)
1C (BSL) Community PluginLANGUAGESCode Analyzer for 1C (BSL)  1.9.0

**Comment by nixel2007** [comment]
Добрый день!

Это не совсем ошибки, это информационные сообщения. В новом релизе оно выводить более полную информацию, это должно помочь легче диагностировать проблему.

Сможете проверить работу на дев-сборке?

**Comment by nagdevops2** [comment]
Подскажите где её взять? В релизах только 1.9.0 версия.

**Comment by nixel2007** [comment]
https://t.me/bsl_language_server/75251

**Comment by nagdevops2** [comment]
Спасибо. Прогнал с этой версией. Стало понятней.

ERROR: Can't compute TextRange for given Range: start(2883, 4), end(2883, 5) of rule: IncorrectLineBreak in file: file:///E:/jenkins/workspace/GitSYNC@2/Trade/CommonModules/УправлениеДенежнымиСредствами/Ext/Module.bsl.
java.lang.IllegalArgumentException: 4 is not a valid line offset for pointer. File Trade/CommonModules/УправлениеДенежнымиСредствами/Ext/Module.bsl has 0 character(s) at line 2884
	at org.sonar.api.utils.Preconditions.checkArgument(Preconditions.java:43)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:339)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:272)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:287)
	at com.github._1c_syntax.bsl.sonar.IssuesLoader.getTextRange(IssuesLoader.java:216)
	at com.github._1c_syntax.bsl.sonar.IssuesLoader.processDiagnostic(IssuesLoader.java:124)
	at com.github._1c_syntax.bsl.sonar.IssuesLoader.createIssue(IssuesLoader.java:103)
	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.lambda$processFile$5(BSLCoreSensor.java:191)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.processFile(BSLCoreSensor.java:191)
	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.lambda$execute$3(BSLCoreSensor.java:166)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

![image](https://user-images.githubusercontent.com/82443902/131818678-733f4ea5-f391-4758-9676-1361cf298ee4.png)

**Comment by nixel2007** [comment]
Можете приложить файл?

**Comment by nagdevops2** [comment]
> Можете приложить файл?

[Module.zip](https://github.com/1c-syntax/sonar-bsl-plugin-community/files/7098241/Module.zip)

**Comment by nixel2007** [comment]
Кажется, вы приложили какой-то другой файл. В этом файле на строке 2883 находится код:

```bsl

		ПараметрыСделкиПоВидуОпераций = Новый Соответствие();

		ПараметрыСделкиПоВидуОпераций.Вставить(Перечисления.ВидыОперацийРКО.ОплатаПоставщику,ЗаказПоставщикуРасход);
		ПараметрыСделкиПоВидуОпераций.Вставить(Перечисления.ВидыОперацийРКО.ВозвратДенежныхСредствПокупателю,ЗаказПокупателяРасход);
```

**Comment by nagdevops2** [comment]
Файл тот, но в разных редакторах не совпадает нумерация кода.

Вот в far
![image](https://user-images.githubusercontent.com/82443902/131861629-bfd4b590-cd7c-4305-ab26-aae9e31361f5.png)

В Notepad++ как вы указали

В Конфигураторе:

![image](https://user-images.githubusercontent.com/82443902/131862179-41c554d5-4d91-4223-91b5-3acb77d934be.png)

**Comment by nixel2007** [comment]
у вас файл содержит одиночные символы CR (возврат каретки) - без предшествующего ему LF (перевода строки). Это формат старых MacOS, который почти во всех современных средах не поддерживается. В большинстве мест в BSL LS эта ситуация обрабатывается корректно, но не конкретно в этой диагностике. спасибо за репорт, я перенесу задачу в репозиторий bsl ls.
