### ISSUE TITLE
[BUG] Ошибка при хайлайте

### ISSUE THREAD

**Issue by sfaqer** [1c-syntax/sonar-bsl-plugin-community#126]
**Версия**
> 0.19.0

**Описание ошибки диагностики**
```
[Step 8/9] INFO: EXECUTION FAILURE
[Step 8/9] INFO: ------------------------------------------------------------------------
[Step 8/9] INFO: Total time: 2:47.760s
[Step 8/9] INFO: Final Memory: 803M/2728M
[Step 8/9] ERROR: Error during SonarScanner execution
[Step 8/9] INFO: ------------------------------------------------------------------------
[Step 8/9] java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Unable to highlight file src/cf/DataProcessors/ФормированиеЗаказовНаОбслуживаниеОС/Ext/ObjectModule.bsl
[Step 8/9] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[Step 8/9] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[Step 8/9] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[Step 8/9] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[Step 8/9] 	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
[Step 8/9] 	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
[Step 8/9] 	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
[Step 8/9] 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
[Step 8/9] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
[Step 8/9] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
[Step 8/9] 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[Step 8/9] 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
[Step 8/9] 	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.lambda$execute$4(BSLCoreSensor.java:161)
[Step 8/9] 	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
[Step 8/9] 	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.execute(BSLCoreSensor.java:144)
[Step 8/9] 	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
[Step 8/9] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
[Step 8/9] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
[Step 8/9] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
[Step 8/9] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
[Step 8/9] 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:79)
[Step 8/9] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
[Step 8/9] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
[Step 8/9] 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:382)
[Step 8/9] 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:378)
[Step 8/9] 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:347)
[Step 8/9] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
[Step 8/9] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
[Step 8/9] 	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:136)
[Step 8/9] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
[Step 8/9] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
[Step 8/9] 	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
[Step 8/9] 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
[Step 8/9] 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
[Step 8/9] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[Step 8/9] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[Step 8/9] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Step 8/9] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[Step 8/9] 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
[Step 8/9] 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
[Step 8/9] 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
[Step 8/9] 	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
[Step 8/9] 	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
[Step 8/9] 	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
[Step 8/9] 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
[Step 8/9] Caused by: java.lang.IllegalArgumentException: Unable to highlight file src/cf/DataProcessors/ФормированиеЗаказовНаОбслуживаниеОС/Ext/ObjectModule.bsl
[Step 8/9] 	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:85)
[Step 8/9] 	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:37)
[Step 8/9] 	at com.github._1c_syntax.bsl.sonar.BSLHighlighter.lambda$saveHighlighting$6(BSLHighlighter.java:177)
[Step 8/9] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[Step 8/9] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[Step 8/9] 	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
[Step 8/9] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[Step 8/9] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[Step 8/9] 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[Step 8/9] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[Step 8/9] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[Step 8/9] 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[Step 8/9] 	at com.github._1c_syntax.bsl.sonar.BSLHighlighter.saveHighlighting(BSLHighlighter.java:176)
[Step 8/9] 	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.processFile(BSLCoreSensor.java:195)
[Step 8/9] 	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.lambda$execute$3(BSLCoreSensor.java:166)
[Step 8/9] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[Step 8/9] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
[Step 8/9] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[Step 8/9] 	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
[Step 8/9] 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
[Step 8/9] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[Step 8/9] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[Step 8/9] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[Step 8/9] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[Step 8/9] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[Step 8/9] Caused by: java.lang.IllegalArgumentException: 21 is not a valid line offset for pointer. File src/cf/DataProcessors/ФормированиеЗаказовНаОбслуживаниеОС/Ext/ObjectModule.bsl has 15 character(s) at line 297
[Step 8/9] 	at org.sonar.api.utils.Preconditions.checkArgument(Preconditions.java:43)
[Step 8/9] 	at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:339)
[Step 8/9] 	at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:272)
[Step 8/9] 	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:288)
[Step 8/9] 	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:83)
[Step 8/9] 	... 24 more
[Step 8/9] ERROR: 
[Step 8/9] ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.
```

**Пример кода**
![image](https://user-images.githubusercontent.com/32082417/133948088-46b58491-231f-451a-a373-b9435f13686b.png)

**Comment by SanyaGerbut** [comment]
У меня эта же ошибка при анализе конфигурации.
Есть какой-то воркераунд?

**Comment by nixel2007** [comment]
@SanyaGerbut поправить оператор, чтобы оба слова были на одной строке, либо попробовать последнюю сборку плагина из телеграм-чата

**Comment by SanyaGerbut** [comment]
> @SanyaGerbut поправить оператор, чтобы оба слова были на одной строке, либо попробовать последнюю сборку плагина из телеграм-чата

Спасибо. Помогло.
