### ISSUE TITLE
Ошибка Unable to highlight file

### ISSUE THREAD

**Issue by nagdevops2** [1c-syntax/sonar-bsl-plugin-community#148]
Здравствуйте.

SonarScanner 4.6.2.2472
SonarQube server 8.8.0
1C (BSL) Community Plugin 1.9.0+13.dev

Ошибка:
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 18:42.894s
INFO: Final Memory: 2327M/7788M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarScanner execution
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Unable to highlight file ERP/CommonModules/CRM_КлиентыСервер/Ext/Module.bsl
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.lambda$execute$4(BSLCoreSensor.java:161)
	at java.base/java.util.HashMap.forEach(Unknown Source)
	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.execute(BSLCoreSensor.java:144)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:392)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:388)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:357)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:149)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.IllegalArgumentException: Unable to highlight file ERP/CommonModules/CRM_КлиентыСервер/Ext/Module.bsl
	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:97)
	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:37)
	at com.github._1c_syntax.bsl.sonar.BSLHighlighter.lambda$saveHighlighting$6(BSLHighlighter.java:177)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.github._1c_syntax.bsl.sonar.BSLHighlighter.saveHighlighting(BSLHighlighter.java:176)
	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.processFile(BSLCoreSensor.java:195)
	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.lambda$execute$3(BSLCoreSensor.java:166)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: 21 is not a valid line offset for pointer. File ERP/CommonModules/CRM_КлиентыСервер/Ext/Module.bsl has 16 character(s) at line 2066
	at org.sonar.api.utils.Preconditions.checkArgument(Preconditions.java:43)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:339)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:272)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:288)
	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:95)
	... 24 more
ERROR: 
ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.

[Module.bsl.gz](https://github.com/1c-syntax/sonar-bsl-plugin-community/files/7623100/Module.bsl.gz)

**Comment by theshadowco** [comment]
Обновите плагин до актуальной версии

**Comment by nagdevops2** [comment]
Обновил. Проблема осталась.

**Comment by theshadowco** [comment]
попробуйте ночную сборку, на ней проблем е обнаружено

**Comment by nagdevops2** [comment]
С ночной сборкой не запускается sq

onarqube    | 2021.12.06 13:43:25 ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed
sonarqube    | java.lang.IllegalStateException: Unable to read plugin manifest from jar : /opt/sonarqube/extensions/plugins/sonar-communitybsl-plugin-nightly-20211206.jar
sonarqube    | 	at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:125)
sonarqube    | 	at org.sonar.server.plugins.ServerPluginInfo.create(ServerPluginInfo.java:37)
sonarqube    | 	at org.sonar.server.plugins.PluginJarLoader.lambda$getExternalPluginsMetadata$5(PluginJarLoader.java:206)
sonarqube    | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
sonarqube    | 	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(Unknown Source)
sonarqube    | 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
sonarqube    | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
sonarqube    | 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
sonarqube    | 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
sonarqube    | 	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
sonarqube    | 	at org.sonar.server.plugins.PluginJarLoader.loadPluginsFromDir(PluginJarLoader.java:236)
sonarqube    | 	at org.sonar.server.plugins.PluginJarLoader.getExternalPluginsMetadata(PluginJarLoader.java:206)
sonarqube    | 	at org.sonar.server.plugins.PluginJarLoader.loadPlugins(PluginJarLoader.java:92)
sonarqube    | 	at org.sonar.server.plugins.ServerPluginManager.start(ServerPluginManager.java:64)
sonarqube    | 	at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
sonarqube    | 	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
sonarqube    | 	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
sonarqube    | 	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
sonarqube    | 	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
sonarqube    | 	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
sonarqube    | 	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
sonarqube    | 	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
sonarqube    | 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
sonarqube    | 	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
sonarqube    | 	at org.sonar.server.platform.platformlevel.PlatformLevel2.start(PlatformLevel2.java:111)
sonarqube    | 	at org.sonar.server.platform.PlatformImpl.start(PlatformImpl.java:213)
sonarqube    | 	at org.sonar.server.platform.PlatformImpl.startLevel2Container(PlatformImpl.java:179)
sonarqube    | 	at org.sonar.server.platform.PlatformImpl.init(PlatformImpl.java:87)
sonarqube    | 	at org.sonar.server.platform.web.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:43)
sonarqube    | 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4705)
sonarqube    | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5171)
sonarqube    | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
sonarqube    | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)
sonarqube    | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)
sonarqube    | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
sonarqube    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
sonarqube    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
sonarqube    | 	at java.base/java.lang.Thread.run(Unknown Source)
sonarqube    | Caused by: java.util.zip.ZipException: zip END header not found
sonarqube    | 	at java.base/java.util.zip.ZipFile$Source.zerror(Unknown Source)
sonarqube    | 	at java.base/java.util.zip.ZipFile$Source.findEND(Unknown Source)
sonarqube    | 	at java.base/java.util.zip.ZipFile$Source.initCEN(Unknown Source)
sonarqube    | 	at java.base/java.util.zip.ZipFile$Source.<init>(Unknown Source)
sonarqube    | 	at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
sonarqube    | 	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
sonarqube    | 	at java.base/java.util.zip.ZipFile$CleanableResource.get(Unknown Source)
sonarqube    | 	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
sonarqube    | 	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
sonarqube    | 	at java.base/java.util.jar.JarFile.<init>(Unknown Source)
sonarqube    | 	at java.base/java.util.jar.JarFile.<init>(Unknown Source)
sonarqube    | 	at java.base/java.util.jar.JarFile.<init>(Unknown Source)
sonarqube    | 	at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:120)
sonarqube    | 	... 37 common frames omitted
sonarqube    | 2021.12.06 13:43:25 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
sonarqube    | 2021.12.06 13:43:25 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process
sonarqube    | 2021.12.06 13:43:25 INFO  app[][o.s.a.SchedulerImpl] Process[web] is stopped
sonarqube    | 2021.12.06 13:43:25 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 143
sonarqube    | 2021.12.06 13:43:25 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
sonarqube    | 2021.12.06 13:43:25 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
