### ISSUE TITLE
Конфликт плагинов

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/sonar-bsl-plugin-community#33]
Думаю стоит указать в документации, что данный плагин и другой конфликтуют, что надо сначала один отключить

**Comment by nixel2007** [comment]
Либо сделать так, чтобы они не конфликтовали. Но это сложнее.

**Comment by asosnoviy** [comment]
А кинь лог плз. Что оно там вещает?

**Comment by nixel2007** [comment]
Либо конфликт регистрации Language с одинаковым ключом, либо конфликт 2 built-in profile на language с одним ключом.

**Comment by theshadowco** [comment]
```
2019.09.23 08:10:35 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Fail to load plugin BSL :: Plugin [bsl]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:543)
	at org.sonar.server.platform.Platform.start(Platform.java:211)
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
	at org.sonar.server.platform.Platform.access$500(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Unable to register extension org.sonar.api.config.PropertyDefinition from plugin 'bsl'
	at org.sonar.core.platform.ComponentContainer.addExtension(ComponentContainer.java:242)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtension(ServerExtensionInstaller.java:119)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:74)
	... 9 common frames omitted
Caused by: org.picocontainer.PicoCompositionException: Duplicate Keys not allowed. Duplicate for 'org.sonar.api.config.PropertyDefinition-sonar.bsl.file.suffixes'
	at org.picocontainer.DefaultPicoContainer.addAdapterInternal(DefaultPicoContainer.java:438)
	at org.picocontainer.DefaultPicoContainer.addAdapter(DefaultPicoContainer.java:459)
	at org.picocontainer.DefaultPicoContainer.addComponent(DefaultPicoContainer.java:556)
	at org.picocontainer.DefaultPicoContainer.access$300(DefaultPicoContainer.java:84)
	at org.picocontainer.DefaultPicoContainer$AsPropertiesPicoContainer.addComponent(DefaultPicoContainer.java:1149)
	at org.sonar.core.platform.ComponentContainer.addExtension(ComponentContainer.java:240)
	... 11 common frames omitted
```

**Comment by theshadowco** [comment]
Не стоит ставить 2 плагина. 
При необходимости использовать результаты анализа BSLLS необходимо запускать его cli режиме перед запуском анализа сонар-плагина от Серебрянной Пули. Полученный отчет указать в параметре конфига сонар плагина.

Подробности использования импорта результатов сторонних анализаторов есть в документации к плагину Серебрянной Пули.
